### ISSUE TITLE
Various warnings

### ISSUE THREAD

**Issue by vandoeselaar** [altcha-org/wordpress-plugin#1]
While the plugin seems to work (thank you!), I receive 70 warnings about undefined variables. Mostly $ALTCHA_WEBSITE from translations.php and a bunch of undefined array keys from options.php. I have attached a screenshot from the Query Monitor output. 

![warnings](https://github.com/altcha-org/wordpress-plugin/assets/21199489/06f5a392-aa5c-4bb5-9fea-be61f58ac71e)

**Comment by ovx** [comment]
Hi, thanks for reporting. Its fixed in version 0.1.2, see Releases.
