### ISSUE TITLE
Change widget language via the shortcode's attributes or Polylang and WPML integration

### ISSUE THREAD

**Issue by Deejay-Ste** [altcha-org/wordpress-plugin#10]
Hello, first of all thanks for this good alternative to reCaptcha and others. I just have a little thing missing in the custom integration for it to be perfect, it's the ability to change the language of the widget via the shortcode's attributes, like `[altcha language="en"]` for exemple. Or it can be a native integration with Polylang and WPML plugins to be able to change the widget's strings on the fly depending of the current active language. I can help with this if needed. Thanks in advance and keep up the good work.

**Comment by ovx** [comment]
Hi, thanks for the suggestion. In the latest version `1.1.0`, the short now supports `[altcha language="de"]`. For supported languages, see https://github.com/altcha-org/wordpress-plugin/blob/main/altcha.php#L22

**Comment by Deejay-Ste** [comment]
Thanks for the quickness ! Works perfectly !
