### ISSUE TITLE
[BUG] on Wordpress 6.6.1

### ISSUE THREAD

**Issue by drum3870** [altcha-org/wordpress-plugin#11]
Altcha 1.3.0 tested on WP 6.6.1 resulted in the following error message 

> Warning: Undefined array key "port" in /wp-content/plugins/altcha-spam-protection/includes/core.php on line 111

Here is the core.php  code area mentioned by the error message (lines 111-112)

```php
$url = wp_parse_url(get_site_url());
AltchaPlugin::$hostname = $url['host'] . ($url['port'] ? ':' . $url['port'] : '');
```

Suggested modification : 

```php
$url = wp_parse_url(get_site_url());
AltchaPlugin::$hostname = $url['host'] . (isset($url['port']) ? ':' . $url['port'] : '');
```
The suggested modification fixes the issue on my instance. 

Note for the devs : thanks for your work and your nice software !

**Comment by ovx** [comment]
Hi and thank you for reporting. The fix is implemented in the version `1.3.1`.
