### ISSUE TITLE
HTML Forms: Malformed AJAX response

### ISSUE THREAD

**Issue by templeman** [altcha-org/wordpress-plugin#15]
When submitting a form built using HTML Forms plugin, ALTCHA appears to be interfering with the HTML Forms AJAX response, causing subsequent events to fail.

Here is an example success response without ALTCHA enabled:

```
{
    "message": {
        "type": "success",
        "text": "Thank you!"
    },
    "hide_form": true
}
```

Here is the success response with ALTCHA enabled (via Shortcode option):

```
<input type="hidden" id="_altchanonce" name="_altchanonce" value="6bfa91d2d1"/>
<input type="hidden" name="_wp_http_referer" value="/wp/wp-admin/admin-ajax.php?action=hf_form_submit"/>{"message":{"type":"success","text":"Thank you!"},"hide_form":true}
```

In the latter case, the response triggers a console error:

```
HTML Forms: failed to parse AJAX response.

Error: "SyntaxError: Unexpected token '<', "<input typ"... is not valid JSON"
```

and the subsequent events fail (form does not hide, success message does not show).

HTML Forms v 1.3.34
ALTCHA Spam Protection v 1.7.0

**Comment by ovx** [comment]
Hi, I'm trying to reproduce this issues, it seems to work fine, tested with mentioned versions and WP 6.6.1.

The HTML nonce is added via `hf_form_html` hook, which should be called only when the form is rendered so I don't see the reason why would it render in the ajax response.

My guess is some other plugin is causing this. Try to disable security or API-related plugins.

**Comment by templeman** [comment]
The issue remains for me, even on a new vanilla install of WordPress with the only two active plugins being HTML Forms and Altcha Spam Protection.

When Altcha is enabled for HTML Forms (Captcha or Shortcode, doesn't matter), the JSON output is polluted. The malformed JSON can be seen in the AJAX response on form submission, and also when attempting to save changes in the block editor when the HTML Forms shortcode is included on the page. When Altcha for HTML Forms is disabled, the JSON response is correct and errors are gone.

HTML Forms 1.3.34
Altcha 1.8.0
WP 6.6.2

https://github.com/user-attachments/assets/de44668b-2d84-4a36-82bb-2119ea4a5a15

**Comment by ovx** [comment]
Still not able to reproduce, but because this seems to be caused by nonces, this should be fixed once they are removed as part of #16 .

**Comment by ovx** [comment]
Try it with the latest version 1.9.0, which removes nonces.

**Comment by templeman** [comment]
I can confirm the issue is gone after updating to 1.9.0. Thank you!
