### ISSUE TITLE
Spam filter attribute not shows up in the html structure of the widget if using shortcode [altcha] implementation

### ISSUE THREAD

**Issue by anton-esin** [altcha-org/wordpress-plugin#17]
We generated free api code an switched spam filter on in the settings. Also for integration we chose Captcha + Spam Filter in the settings, but in the html structure of the widget on page we see only blockspam="1" and no spamfilter attribute at all. We integrate it via shortcode inside of the form of the Jetforms plugin from Crocoblock.

Could it be that the spam filter protection is not activated in this case? 

If we change the shortcode from [altcha] to [altcha mode="captcha_spamfilter"],  then the attribute spamfilter="1" shows up in the html code, if it is neccessary it wasn't clear from documentation and backend info of the plugin (or we failed to find it, what also possible).
 
![image](https://github.com/user-attachments/assets/4f0d67c4-4f1a-47d3-8225-d565fe511879)
![image](https://github.com/user-attachments/assets/6eec7034-2da7-4ab5-bc3d-09463ab64057)

**Comment by ovx** [comment]
Hi, thank you for reporting. It's fixed in the latest version `1.8.0`, the shortcode now automatically detects the selected mode .
