### ISSUE TITLE
Wrong position of widget on Contact Form 7

### ISSUE THREAD

**Issue by jkummer** [altcha-org/wordpress-plugin#18]
The widget is displayed below the submit button when using Contact Form 7.
After checking the code, I would suggest the problem is in integrations/contact-form-7.php where the button to find is defined as
`$button = '<input class="wpcf7-form-control wpcf7-submit ';`
but should be
`$button = '<button class="wpcf7-form-control wpcf7-submit ';`
because Contact Form 7 in the actual version is using <button> for submitting.

**Comment by ovx** [comment]
Hi, I have CF7 5.9.8 (seems to be the latest version) and it still uses `<input>` (not sure if that's something configurable, but input seems to be default). But the latest version 1.9.0 of the plugin now supports both types and if you need more flexibility, you can select `Shortcode` option for CF7 and use `[altcha]` shortcode anywhere in the markup.

**Comment by jkummer** [comment]
Thanks for the update. Works perfect. I will close this thicket as resolved
