### ISSUE TITLE
contact-form-7.php integration use str_contains, turn plugin require php8+

### ISSUE THREAD

**Issue by roberto-ayala** [altcha-org/wordpress-plugin#20]
# Issue: PHP 8+ Requirement Due to str_contains Usage in contact-form-7.php Integration

### Description:

The Altcha plugin integration with contact-form-7.php utilizes the str_contains function, which was introduced in PHP 8.0. As a result, this introduces a strict PHP 8+ requirement for the plugin to function correctly.

### Impact:

The plugin will break in environments running PHP 7.x or lower due to the missing str_contains function.
This issue forces users to upgrade their PHP version to 8+ if they want to continue using the plugin without errors.

### Steps to Reproduce:

Install the Altcha plugin in a WordPress environment running PHP 7.x.
Enable the contact-form-7 integration.
Observe the fatal error due to the str_contains function.

### Expected Behavior:

The plugin should either:

Check the PHP version before using str_contains and provide compatibility for older versions of PHP (e.g., by using strpos as a fallback).
Clearly document that the plugin requires PHP 8+ to work properly.

### Proposed Solution:

Replace str_contains with a backward-compatible alternative like strpos or add a version check to ensure compatibility with PHP 7.x.
Update the plugin documentation to reflect the PHP version requirements.

[Pull Request with proposal](https://github.com/altcha-org/wordpress-plugin/pull/19)

**Comment by ovx** [comment]
Hi, thanks for your PR, merged and released as 1.9.1.
