### ISSUE TITLE
HTML Forms: Challenge enforced regardless of shortcode presence

### ISSUE THREAD

**Issue by templeman** [altcha-org/wordpress-plugin#23]
When enabling Altcha for HTML Forms using the shortcode method, Altcha enforcement is applied globally to all "HTML Forms" instances, regardless of whether they include the [altcha] shortcode.

- Form 1 with [altcha] shortcode
**Checkbox is present and verification is required for form submission (as expected).**

- Form 2 on a different page without [altcha] shortcode
**Checkbox is not present but verification is still required for form submission, resulting in no submissions.**

Ideally the plugin would only enforce verification when the shortcode is present.

This is probably not a very common use case but I figured I would flag it here.

WP: 6.6.2
ALTCHA: 1.11.1
HTML Forms: 1.4.0

**Comment by ovx** [comment]
Hi, thanks for the suggestions, it's implemented in version 1.12.0. If the shortcode isn't located in the form markup, the verification is skipped.
