### ISSUE TITLE
Example on how to verify Solution

### ISSUE THREAD

**Issue by andreas83** [altcha-org/wordpress-plugin#29]
I added the shortcode [altcha] to one of my forms, the data is then send to the server where the hidden altcha payload needs to be validated. 
Would be nice to have a short example for this use case. 

I guess its something like or similar: 

```
	$payload=json_decode(base64_decode($payload), true);
	$payload['number'] = $_SESSION['randNumber'];
	$data= Altcha::verifySolution($payload, $this->hmacKey, true);
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new function `altcha_verify_solution` to demonstrate how to validate the ALTCHA payload on the server side. This addresses the GitHub issue requesting an example for this use case.

You can review changes in this commit: https://github.com/mnmnk43434/altcha-org-wordpress-plugin-29/commit/7bbfef7508b07c71a611251653a0b5b6847cca52.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
