### ISSUE TITLE
Default to page locale

### ISSUE THREAD

**Issue by rimas-kudelis** [altcha-org/wordpress-plugin#31]
The plugin currently requires selecing a language in which it will be shown.

It would be great if that language could be detected from current website/page language, and default to that setting. Let's not forget that some WordPress installations are multilingual, and for them tying the captcha to only one language is not ideal.

**Comment by ovx** [comment]
Hi, thanks for the suggestion. Implemented in version 1.14.0.

To activate, select `Auto` from the Language select in the plugin's settings.

**Comment by rimas-kudelis** [comment]
amazing, thanks!
