### ISSUE TITLE
Add link to settings in plugin's entry in the plugin list

### ISSUE THREAD

**Issue by rimas-kudelis** [altcha-org/wordpress-plugin#32]
Most/many plugins put a link to their settings next to their entry in the plugin list. This makes it easier to find where the specific plugin is to be configured.

IMO, the Altcha plugin should do that too.

![paveikslas](https://github.com/user-attachments/assets/51e8709d-5102-4b53-b6f0-6a24210831bc)

**Comment by ovx** [comment]
Hi, the settings link was already there, but placed as the last item. The placement changed in the version 1.14.0.

**Comment by rimas-kudelis** [comment]
@ovx, somehow it's not actually there even after the update.
In my screenshot, only the disable link is there. And it's the same after updating to 1.14.0. Does this work for you?

**Comment by ovx** [comment]
@rimas-kudelis you're right, it was working for me only because I had it installed in `altcha` directory, but the WP directory installs it to a different one.  Fixed in 1.14.1.
