### ISSUE TITLE
Error for "lost password" form

### ISSUE THREAD

**Issue by Eumed** [altcha-org/wordpress-plugin#4]
Hello,

Thank you for the interesting initiative.
0.1.2 generates the error "Cannot submit your message" for WordPress "lost password" feature.
Undefined property: stdClass::$verificationData in [...] \wp-content\plugins\altcha-plugin\includes\core.php on line 222

**Comment by ovx** [comment]
Hello, thanks for reporting. It's fixed in version 0.1.3, see Releases.

**Comment by Eumed** [comment]
> Hello, thanks for reporting. It's fixed in version 0.1.3, see Releases.

It's working fine. Thank you.
