### ISSUE TITLE
WordPress Plugin Repository

### ISSUE THREAD

**Issue by D0nVit0** [altcha-org/wordpress-plugin#6]
Hello, 

Will this plugin be available in the WordPress Plugin Repository? Alternatively, is there another way to receive notifications about updates in the WordPress dashboard, or possibly enable automatic updates?

Thank you.

**Comment by ovx** [comment]
Hello, the plugin has been submitted to the Wordpress Plugin repository, but it's still under review. I expect it should be published within days.
