### ISSUE TITLE
Accessibility improvement

### ISSUE THREAD

**Issue by D0nVit0** [altcha-org/wordpress-plugin#7]
Any chance to add a discernible name to the altcha-logo?

_Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users._ 

https://dequeuniversity.com/rules/axe/4.9/link-name

**Comment by ovx** [comment]
Hi, sorry for the delay. Yes, it should be added for sure. I added a new translation string for this `ariaLinkLabel` allowing customization. Not sure if the default "Visit Altcha.org" is enough, please provide feedback on this.

Implemented in the `next` branch: https://github.com/altcha-org/altcha/commit/da89420e1d5d1beafafd662cbe2813b002891af1#diff-1a6798607b0fe5453e7855dfcea64eca8d1575e764c9be76696ac2e49283a490

**Comment by ovx** [comment]
It hasn't been merged and released yet, will release to the web component first and shortly after to the wordpress plugin.
