### ISSUE TITLE
WP-Plugin Forminator Multi-Step Forms

### ISSUE THREAD

**Issue by floristweb** [altcha-org/wordpress-plugin#8]
I am trying to use the ALTCHA WP Plugin in Self-hosted Mode with my Forminator Forms. All works well with One-Page Forms.
But my Multi-Step Form gives a "Cannot submit your message" Error.

Behaviour:
ALTCHA Widget not visible on any of the steps / pages
Form is fillable
On final submit, an error box appears on top of the form saying: Cannot submit your message.

![8766](https://github.com/altcha-org/wordpress-plugin/assets/128612046/c5a4c46e-e0a6-4372-b291-75ac8a731839)

If I manually add a [altcha] Shortcode, it displays plain - as if undefined:
![33192](https://github.com/altcha-org/wordpress-plugin/assets/128612046/612f62dc-ffb8-471c-9d82-f1c191f17fd7)

What is wrong?
Thank you for help
Lin

**Comment by ovx** [comment]
Hi, I tested it with multi-step forms, it's a problem with the plugin, will look into it soon.

**Comment by ovx** [comment]
Fixed in `0.1.7` version (https://github.com/altcha-org/wordpress-plugin/releases/tag/0.1.7).

**Comment by floristweb** [comment]
Thank you very much! Works like a charm.
