### ISSUE TITLE
401 error with Self hosted mode

### ISSUE THREAD

**Issue by floristweb** [altcha-org/wordpress-plugin#9]
Plugin v 0.2.1 works fine on 1 website (https://floristweb.de/persoenliches-angebot/) - but there is a 401 error on my other website https://blumentempel.de/kontakt/ causing the challenge to fail - I am sorry, what can I do as I have tried all the settings in the plugin settings.

**Comment by ovx** [comment]
Hi, the API endpoint returns "The REST API has been restricted to authenticated users.", which I think is caused by one of the "Disable REST API" plugins. Look for a similar plugin you already installed and try to deactivate it.

**Comment by floristweb** [comment]
thanks a lot! That helped!

**Comment by zenminimalist** [comment]
Just to add: I had the same problem with Perfmatters. Fix it for me. Just in case someone in the future (*great Scott!*) read this 😀
